# Generated by Django 5.2.11 on 2026-02-13 02:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('chunk_index', models.PositiveIntegerField(default=0, help_text='Ordering index within interview')),
                ('speaker_label', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment score -1.0 to 1.0', null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='interviews.interview')),
            ],
            options={
                'db_table': 'transcript_chunks',
                'ordering': ['interview', 'chunk_index'],
                'indexes': [models.Index(fields=['interview', 'chunk_index'], name='idx_chunk_interview_order'), models.Index(fields=['interview', 'start_time'], name='idx_chunk_interview_time'), models.Index(fields=['interview', 'is_deleted'], name='idx_chunk_interview_active'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_chunk_search_vector'), models.Index(condition=models.Q(('sentiment_score__isnull', False)), fields=['interview', 'sentiment_score'], name='idx_chunk_sentiment')],
                'constraints': [models.UniqueConstraint(fields=('interview', 'chunk_index'), name='uq_chunk_interview_index'), models.CheckConstraint(condition=models.Q(('start_time__gte', 0)), name='ck_chunk_start_time_positive'), models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time'))), name='ck_chunk_end_after_start'), models.CheckConstraint(condition=models.Q(('sentiment_score__isnull', True), models.Q(('sentiment_score__gte', -1.0), ('sentiment_score__lte', 1.0)), _connector='OR'), name='ck_chunk_sentiment_range')],
            },
        ),
    ]
