# Generated by Django 5.2.11 on 2026-02-13 02:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_project_user_created'), models.Index(fields=['user', 'is_deleted'], name='idx_project_user_active'), models.Index(fields=['name'], name='idx_project_name')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'name'), name='uq_project_user_name_active')],
            },
        ),
    ]
