# Generated by Django 5.2.11 on 2026-02-13 02:44

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embeddings', '0001_enable_pgvector'),
        ('interviews', '0001_initial'),
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', pgvector.django.vector.VectorField(dimensions=1536)),
                ('model_name', models.CharField(default='text-embedding-3-small', help_text='Embedding model used to generate this vector', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='interviews.interview')),
                ('transcript_chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='transcription.transcriptchunk')),
            ],
            options={
                'db_table': 'embeddings',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='idx_embedding_vector_cosine', opclasses=['vector_cosine_ops']), models.Index(fields=['interview'], name='idx_embedding_interview')],
            },
        ),
    ]
