# Generated by Django 5.2.11 on 2026-02-13 02:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file_url', models.URLField(max_length=2048)),
                ('file_name', models.CharField(default='', max_length=512)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('file_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash of the uploaded file for duplicate detection', max_length=64)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('embedding', 'Embedding'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='projects.project')),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='idx_interview_project_created'), models.Index(fields=['project', 'processing_status'], name='idx_interview_project_status'), models.Index(fields=['processing_status'], name='idx_interview_status'), models.Index(fields=['project', 'is_deleted'], name='idx_interview_project_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('file_size__gte', 0)), name='ck_interview_file_size_positive'), models.CheckConstraint(condition=models.Q(('duration_seconds__isnull', True), ('duration_seconds__gte', 0), _connector='OR'), name='ck_interview_duration_positive')],
            },
        ),
    ]
