# Generated by Django 5.2.11 on 2026-02-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='processing_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Processing progress 0–100'),
        ),
    ]
