# Generated by Django 5.2.11 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_interview_processing_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("file", "File Upload"),
                    ("transcript", "Manual Transcript"),
                    ("link", "Media Link"),
                ],
                db_index=True,
                default="file",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="file_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
    ]
