# Generated by Django 5.2.11 on 2026-02-13 02:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightReport',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('feature_requests', 'Top Feature Requests'), ('frustrations', 'Most Common Frustrations'), ('positive_themes', 'Positive Themes'), ('negative_themes', 'Negative Themes'), ('onboarding', 'Onboarding Issues'), ('full', 'Full Report')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict, help_text='Structured report JSON')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Report generation metadata')),
                ('processing_error', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_reports', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insight_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'report_type', '-created_at'], name='idx_report_project_type'), models.Index(fields=['project', 'status'], name='idx_report_project_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'completed', 'failed'])), name='ck_report_valid_status')],
            },
        ),
    ]
